apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: playeconomybkm.azurecr.io/play.catalog:1.0.2
        env:
            - name: ServiceSettings__MessageBroker
              value: SERVICEBUS
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: catalog-secrets
                  key: cosmosdb-connectionstring
            - name: ServiceBusSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: catalog-secrets
                  key: servicebus-connectionstring
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  type: LoadBalancer
  selector:
    app: catalog
  ports:
  - port: 88
    targetPort: 5000
